# Generated by Django 5.2 on 2025-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_historicalblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalBlock',
        ),
    ]
